include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - "lib/generated/**"

  errors:
    # Freezed 관련 - extension import 누락 시 에러 처리
    undefined_method: error

    # 중요한 에러들을 warning에서 error로 승격
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # 코드 스타일
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_print: true
    avoid_returning_null_for_void: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # 에러 방지
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

    # Clean Code
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    no_duplicate_case_values: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Riverpod & Functional Programming
    prefer_function_declarations_over_variables: true

    # 주석 및 문서화
    package_api_docs: false  # 공개 API 아닌 경우 비활성화
    public_member_api_docs: false  # 개발 초기에는 비활성화
